apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
spec:
  selector:
    matchLabels:
      app: bankapp
  replicas: 2
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: hemanthkumar93/bankapp:latest # Updated image to private DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred # Reference to the Docker registry secret
---
apiVersion: v1
kind: Service
metadata:
  name: blankapp-svc
spec:
  selector:
    app: bankapp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer
